const http=require('node:http');
const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
const {Pool}=require('pg');
const PORT=Number(process.env.PORT||8080);
const ROOT=path.join(__dirname,'..');
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_SSL==='true'?{rejectUnauthorized:false}:undefined});
function json(res,s,b){res.writeHead(s,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(b));}
function body(req){return new Promise((ok,no)=>{let a=[];req.on('data',c=>a.push(c));req.on('end',()=>{try{ok(JSON.parse(Buffer.concat(a).toString()||'{}'))}catch(e){no(e)}});req.on('error',no)})}
function hash(p,s){const x=s?Buffer.from(s,'base64'):crypto.randomBytes(16);return {salt:x.toString('base64'),hash:crypto.scryptSync(String(p),x,64).toString('base64')}}
function eq(a,b){try{a=Buffer.from(a,'base64');b=Buffer.from(b,'base64');return a.length===b.length&&crypto.timingSafeEqual(a,b)}catch{return false}}
function token(){return crypto.randomBytes(32).toString('base64url')}
function th(t){return crypto.createHash('sha256').update(t).digest('hex')}
function cookies(req){const o={};for(const p of String(req.headers.cookie||'').split(';')){const i=p.indexOf('=');if(i>0)o[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1))}return o}
async function auth(req,res){const t=cookies(req).fbi_staff_session;if(!t){json(res,401,{ok:false,error:'Please sign in.'});return null}const q=await pool.query('SELECT username,display_name FROM portal_sessions WHERE token_hash=$1 AND expires_at>$2',[th(t),Date.now()]);if(!q.rows[0]){json(res,401,{ok:false,error:'Please sign in.'});return null}return q.rows[0]}
async function state(c){const q=await c.query('SELECT state_json FROM app_state WHERE id=1');if(!q.rows[0])throw Error('Central database is not initialized');return typeof q.rows[0].state_json==='string'?JSON.parse(q.rows[0].state_json):q.rows[0].state_json}
function iid(p){return p+'-'+Date.now().toString(36)+'-'+crypto.randomBytes(4).toString('hex')}
function nextInv(s){let m=0;for(const x of s.data.data){const z=String(x.no||'').match(/(\d+)$/);if(z)m=Math.max(m,+z[1])}return Math.max(+s.data.settings.invoiceSequence||1,m+1)}
function nextRec(s){let m=0;for(const x of s.data.data)for(const p of x.payments||[]){const z=String(p.receiptNo||'').match(/(\d+)$/);if(z)m=Math.max(m,+z[1])}return m+1}
async function init(){await pool.query('CREATE TABLE IF NOT EXISTS portal_users(id BIGSERIAL PRIMARY KEY,username TEXT UNIQUE NOT NULL,display_name TEXT NOT NULL,password_salt TEXT NOT NULL,password_hash TEXT NOT NULL,active BOOLEAN DEFAULT TRUE);CREATE TABLE IF NOT EXISTS portal_sessions(token_hash TEXT PRIMARY KEY,user_id BIGINT REFERENCES portal_users(id) ON DELETE CASCADE,username TEXT NOT NULL,display_name TEXT NOT NULL,created_at BIGINT NOT NULL,expires_at BIGINT NOT NULL)')}
async function register(req,res){const b=await body(req),u=String(b.username||'').trim().toLowerCase(),n=String(b.name||'').trim(),p=String(b.password||'');if(!/^[a-z0-9._-]{3,40}$/.test(u)||n.length<2||p.length<8)return json(res,400,{ok:false,error:'Enter a valid name, username and password of at least 8 characters.'});if((await pool.query('SELECT 1 FROM portal_users WHERE username=$1',[u])).rowCount)return json(res,409,{ok:false,error:'Username already exists.'});const h=hash(p),q=await pool.query('INSERT INTO portal_users(username,display_name,password_salt,password_hash) VALUES($1,$2,$3,$4) RETURNING id,username,display_name',[u,n,h.salt,h.hash]);return createSession(q.rows[0],res)}
async function createSession(u,res){const t=token(),now=Date.now();await pool.query('INSERT INTO portal_sessions(token_hash,user_id,username,display_name,created_at,expires_at) VALUES($1,$2,$3,$4,$5,$6)',[th(t),u.id,u.username,u.display_name,now,now+43200000]);res.setHeader('Set-Cookie','fbi_staff_session='+encodeURIComponent(t)+'; HttpOnly; SameSite=Lax; Path=/; Max-Age=43200; Secure');return json(res,200,{ok:true,user:u})}
async function login(req,res){const b=await body(req),u=String(b.username||'').trim().toLowerCase(),q=await pool.query('SELECT * FROM portal_users WHERE username=$1 AND active=true',[u]);if(!q.rows[0])return json(res,401,{ok:false,error:'Invalid username or password.'});const h=hash(String(b.password||''),q.rows[0].password_salt);if(!eq(h.hash,q.rows[0].password_hash))return json(res,401,{ok:false,error:'Invalid username or password.'});return createSession(q.rows[0],res)}
async function getData(req,res){
  const u=await auth(req,res); if(!u)return;
  const s=await state(pool);
  json(res,200,{ok:true,user:u,clients:Array.isArray(s.data.clients)?s.data.clients:[],settings:{biz:s.data.settings.biz,bphone:s.data.settings.bphone,bemail:s.data.settings.bemail,logo:'/assets/fbi-logo.jpg'}});
}
async function findInvoice(req,res){
  const u=await auth(req,res); if(!u)return;
  const no=String(new URL(req.url,'http://localhost').searchParams.get('no')||'').trim().toUpperCase();
  if(!no)return json(res,400,{ok:false,error:'Enter an invoice number.'});
  const s=await state(pool),x=s.data.data.find(v=>String(v.no||'').toUpperCase()===no);
  if(!x)return json(res,404,{ok:false,error:'Invoice not found.'});
  const paid=(x.payments||[]).reduce((a,p)=>a+(+p.amount||0),0);
  json(res,200,{ok:true,invoice:{id:x.id,no:x.no,client:x.client,clientPhone:x.clientPhone||'',clientEmail:x.clientEmail||'',date:x.date,total:+x.total||0,paid,balance:Math.max(0,(+x.total||0)-paid),status:x.status||'Draft'}});
}
async function createInvoice(req,res){const u=await auth(req,res);if(!u)return;const b=await body(req),name=String(b.clientName||'').trim(),items=(b.items||[]).map(x=>({desc:String(x.desc||''),qty:+x.qty||0,days:+x.days||1,rate:+x.rate||0})).filter(x=>x.desc&&x.qty>0);if(!name||!items.length)return json(res,400,{ok:false,error:'Client and at least one item are required.'});const c=await pool.connect();try{await c.query('BEGIN');await c.query('SELECT pg_advisory_xact_lock(492020)');const s=await state(c),n=nextInv(s),no='INV'+String(n).padStart(4,'0');let cl=s.data.clients.find(x=>String(x.id)===String(b.clientId||''));if(!cl){cl={id:iid('client'),name,phone:String(b.phone||''),email:String(b.email||''),address:String(b.address||'')};s.data.clients.push(cl)}const rows=items.map(x=>({...x,total:+(x.rate*x.qty*x.days).toFixed(2)})),total=+rows.reduce((a,x)=>a+x.total,0).toFixed(2),inv={id:iid('inv'),no,date:String(b.date||new Date().toISOString().slice(0,10)),due:'On Receipt',client:name,clientId:cl.id,clientPhone:cl.phone||'',clientEmail:cl.email||'',cur:'GHS',items:rows,subtotal:total,discount:0,tax:0,total,status:'Draft',payments:[],amountPaid:0,createdBy:u.username,createdByName:u.display_name,createdAt:new Date().toISOString()};s.data.data.unshift(inv);s.data.settings.invoiceSequence=n+1;s.savedAt=Date.now();await c.query('UPDATE app_state SET version=$1,saved_at=$2,state_json=$3::jsonb WHERE id=1',[Math.max(+s.version||1,4),s.savedAt,JSON.stringify(s)]);await c.query('COMMIT');json(res,200,{ok:true,invoice:inv})}catch(e){try{await c.query('ROLLBACK')}catch{}json(res,500,{ok:false,error:e.message})}finally{c.release()}}
async function pay(req,res){const u=await auth(req,res);if(!u)return;const b=await body(req),amt=+b.amount||0,c=await pool.connect();try{await c.query('BEGIN');await c.query('SELECT pg_advisory_xact_lock(492021)');const s=await state(c),x=s.data.data.find(v=>String(v.id)===String(b.invoiceId||''))||s.data.data.find(v=>String(v.no||'').toUpperCase()===String(b.invoiceNo||'').trim().toUpperCase());if(!x)return json(res,404,{ok:false,error:'Invoice not found.'});const paid=(x.payments||[]).reduce((a,p)=>a+(+p.amount||0),0),bal=Math.max(0,(+x.total||0)-paid);if(amt<=0||amt>bal+.005)return json(res,400,{ok:false,error:'Invalid payment amount.'});const rn=nextRec(s),no='REC'+String(rn).padStart(4,'0'),p={id:iid('pay'),receiptNo:no,amount:amt,date:String(b.date||new Date().toISOString().slice(0,10)),method:String(b.method||'Payment'),transactionRef:String(b.reference||''),receivedBy:u.display_name,balanceAfter:+(bal-amt).toFixed(2),recordedBy:u.username,recordedByName:u.display_name,createdAt:new Date().toISOString()};x.payments=x.payments||[];x.payments.push(p);x.amountPaid=paid+amt;x.receiptNo=no;s.data.settings.receiptSequence=rn+1;x.paymentDate=p.date;x.paymentMethod=p.method;x.transactionRef=p.transactionRef;x.receivedBy=p.receivedBy;x.status=x.amountPaid>=+x.total-.005?'Paid':'Partially Paid';x.updatedAt=new Date().toISOString();s.savedAt=Date.now();await c.query('UPDATE app_state SET version=$1,saved_at=$2,state_json=$3::jsonb WHERE id=1',[Math.max(+s.version||1,4),s.savedAt,JSON.stringify(s)]);await c.query('COMMIT');json(res,200,{ok:true,payment:p,invoice:{id:x.id,no:x.no,client:x.client,total:+x.total||0,paid:+x.amountPaid||0,balance:Math.max(0,(+x.total||0)-(+x.amountPaid||0)),status:x.status||'Draft'}})}catch(e){try{await c.query('ROLLBACK')}catch{}json(res,500,{ok:false,error:e.message})}finally{c.release()}}
function staticFile(res,p){const f=p==='/staff-portal.html'?path.join(__dirname,'staff-portal.html'):p==='/assets/fbi-logo.jpg'?path.join(ROOT,'assets/fbi-logo.jpg'):null;if(!f||!fs.existsSync(f))return false;res.writeHead(200,{'Content-Type':p.endsWith('.jpg')?'image/jpeg':p.endsWith('.js')?'application/javascript; charset=utf-8':'text/html; charset=utf-8'});fs.createReadStream(f).pipe(res);return true}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(req.method==='GET'&&(u.pathname==='/'||u.pathname==='/staff-portal.html')&&staticFile(res,'/staff-portal.html'))return;if(req.method==='GET'&&staticFile(res,u.pathname))return;if(u.pathname==='/api/portal/register'&&req.method==='POST')return register(req,res);if(u.pathname==='/api/portal/login'&&req.method==='POST')return login(req,res);
if(u.pathname==='/api/portal/logout'&&req.method==='POST'){const t=ck(req).fbi_staff_session;if(t)await pool.query('DELETE FROM portal_sessions WHERE token_hash=$1',[th(t)]);res.setHeader('Set-Cookie','fbi_staff_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0; Secure');return json(res,200,{ok:true})}if(u.pathname==='/api/portal/me'&&req.method==='GET'){const u=await auth(req,res);if(u)return json(res,200,{ok:true,user:u});return}if(u.pathname==='/api/portal/data'&&req.method==='GET')return getData(req,res);if(u.pathname==='/api/portal/invoice'&&req.method==='GET')return findInvoice(req,res);if(u.pathname==='/api/portal/invoices'&&req.method==='POST')return createInvoice(req,res);if(u.pathname==='/api/portal/payments'&&req.method==='POST')return pay(req,res);if(u.pathname==='/api/health')return json(res,200,{ok:true,application:'FBI Invoice Portal'});return json(res,404,{ok:false,error:'Not found'})}catch(e){json(res,500,{ok:false,error:e.message})}});
init().then(()=>server.listen(PORT,'0.0.0.0',()=>console.log('FBI Invoice Portal listening on '+PORT))).catch(e=>{console.error(e);process.exit(1)})