const fs = require('node:fs');
const path = require('node:path');
const root = __dirname;
const dir = path.join(root, 'deploy');
const names = fs.readdirSync(dir);
const parts = names.filter(function (n) { return n.indexOf('index.part.') === 0; });
parts.sort(function (a, b) { return a.localeCompare(b, undefined, { numeric: true }); });
if (!parts.length) throw new Error('Invoice Studio source parts are missing');
const html = parts.map(function (n) { return fs.readFileSync(path.join(dir, n), 'utf8'); }).join('');
fs.writeFileSync(path.join(root, 'index.html'), html, 'utf8');
console.log('Built index.html from ' + parts.length + ' source parts (' + html.length + ' bytes).');